services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: simple-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - simple-network

  frontend:
    build:
      dockerfile: frontend/Dockerfile
    container_name: simple-frontend
    ports:
      - "3000:3000"
    networks:
      - simple-network
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

networks:
  simple-network:
    driver: bridge
